/* Generated by Yosys 0.45+11 (git sha1 e8951aba29faf774e475f20c1405162993235d7f, g++ 14.2.1 -O2 -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

(* top =  1  *)
(* generator = "Amaranth" *)
module top(itype, u_ctrl, rd_addr, rm_addr, is_imm, value, instruction);
  input [31:0] instruction;
  wire [31:0] instruction;
  output is_imm;
  wire is_imm;
  output [1:0] itype;
  wire [1:0] itype;
  output [3:0] rd_addr;
  wire [3:0] rd_addr;
  output [3:0] rm_addr;
  wire [3:0] rm_addr;
  output [5:0] u_ctrl;
  wire [5:0] u_ctrl;
  output [14:0] value;
  wire [14:0] value;
  assign itype = instruction[31:30];
  assign u_ctrl = instruction[29:24];
  assign rd_addr = instruction[23:20];
  assign rm_addr = instruction[19:16];
  assign is_imm = instruction[15];
  assign value = instruction[14:0];
endmodule

